2019-08-07 15:22:59,875 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:43]
2019-08-07 15:23:38,682 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:43]
2019-08-07 15:23:49,725 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:43]
2019-08-07 15:27:16,103 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:43]
2019-08-07 15:31:28,088 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:43]
2019-08-07 15:31:51,996 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:43]
2019-08-07 15:32:05,322 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:43]
2019-08-07 16:46:25,004 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:47]
2019-08-07 17:13:06,845 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:49]
2019-08-08 10:18:23,584 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:52]
2019-08-08 10:18:26,444 ERROR: Exception on / [GET] [in /Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/Users/tundelaura/Desktop/blog/app/routes.py", line 17, in before_request
    g.locale = str(get_locale())
NameError: name 'g' is not defined
2019-08-08 10:20:36,473 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:52]
2019-08-08 10:23:11,948 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:52]
2019-08-08 10:24:35,574 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:52]
2019-08-08 13:33:56,915 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:85]
2019-08-08 13:34:07,339 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:85]
2019-08-08 13:37:35,850 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:85]
2019-08-08 13:37:37,926 ERROR: Exception on /auth/login [GET] [in /Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tundelaura/Desktop/blog/app/auth/routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/tundelaura/Desktop/blog/app/templates/base.html", line 86, in template
    {% block content %}
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/tundelaura/Desktop/blog/app/templates/auth/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/tundelaura/Desktop/blog/app/templates/base.html", line 86, in template
    {% block content %}
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/jinja2/environment.py", line 543, in _generate
    optimized=self.optimized)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/jinja2/compiler.py", line 82, in generate
    generator.visit(node)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/jinja2/compiler.py", line 718, in visit_Template
    self.fail('block %r defined twice' % block.name, block.lineno)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/jinja2/compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2019-08-08 13:39:48,832 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:85]
2019-08-08 13:40:19,190 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:85]
2019-08-12 10:13:32,575 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:85]
