2019-08-12 12:21:11,023 ERROR: Exception on /search [GET] [in /Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/tundelaura/Desktop/blog/app/main/routes.py", line 147, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/Users/tundelaura/Desktop/blog/app/models.py", line 20, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/tundelaura/Desktop/blog/app/search.py", line 30, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')
2019-08-12 12:21:37,616 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:86]
2019-08-12 12:21:41,132 ERROR: Exception on /search [GET] [in /Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/tundelaura/Desktop/blog/app/main/routes.py", line 147, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/Users/tundelaura/Desktop/blog/app/models.py", line 20, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/tundelaura/Desktop/blog/app/search.py", line 30, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')
2019-08-12 12:22:32,920 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:86]
2019-08-12 12:22:36,370 ERROR: Exception on /search [GET] [in /Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/tundelaura/Desktop/blog/app/main/routes.py", line 147, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/Users/tundelaura/Desktop/blog/app/models.py", line 20, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/tundelaura/Desktop/blog/app/search.py", line 30, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/tundelaura/Desktop/blog/env/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')
2019-08-12 13:04:42,874 INFO: MyBlog startup [in /Users/tundelaura/Desktop/blog/app/__init__.py:86]
